theme: minima

permalink: /:path/:basename/

header_pages:
  - rulebook.md
  - visual-gallery.md
  - game-dynamics.md
  - flowcharts.md
  - analysis.md
  - playtest-log.md
  - minutes.md
  - contributions.md
  - original-idea.md
